version : "3"
services : 
        java :                                          # which builds the app we will be testing 
                container_name : java
                build : ./java
                ports : 
                        - "8082:8080"
        sel :                                           # which creates the pool of browsers to open the java app 
                container_name : selenium-hub
                image : selenium/hub
                ports : 
                        - "4444:4444"
                depends_on : 
                        - java
        chrome : 
                container_name : chrome
                image : selenium/node-chrome-debug
                depends_on : 
                        - sel                           # service
                environment :
                        - HUB_HOST=selenium-hub         # container_name
                        - HUB_PORT=4444
                volumes : 
                        - /dev/shm/:/dev/shm
                ports : 
                        - "5900:5900"

        firefox : 
                container_name : firefox
                image : selenium/node-firefox-debug
                depends_on : 
                        - sel
                environment : 
                        - HUB_HOST=selenium-hub
                        - HUB_PORT=4444
                volumes : 
                        - /dev/shm:/dev/shm
                ports : 
                        - "5901:5900"
        test :                                          # the tester : will prepare an environment with the test tool and test cases  
                container_name : test-env               #                to be performed by selenium-hub
                build : ./test-env
                volumes : 
                        - ./test:/test                  # volume contains test cases 
                        - ./report:/report:rw           # volume will hold the test results
                depends_on : 
                        - sel
                working_dir : /test
                command : selenium-side-runner  java.side --server http://selenium-hub:4444/wd/hub -c "browserName='chrome'" --output-directory=/report --output-format=junit 
